kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8080    # ← main (active version)
      - containerPort: 30081
        hostPort: 8081    # ← always blue
      - containerPort: 30082
        hostPort: 8082    # ← always green