spring.application.name=jagir

spring.mongodb.uri=mongodb://localhost:27017/jobportal
spring.mongodb.database=jobportal

# Enable auditing for createdAt and updatedAt
spring.data.mongodb.auto-index-creation=true