apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jobportal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/himal77/jobportal   # ← your repo
    targetRevision: main
    path: k8s                                        # ← folder with your manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true       # ← deletes removed resources
      selfHeal: true    # ← fixes manual changes
    syncOptions:
      - CreateNamespace=true