apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobportal-green
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobportal
      version: green
  template:
    metadata:
      labels:
        app: jobportal
        version: green
    spec:
      containers:
        - name: jobportal
          image: himal77/jobportal:3.3.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080