# k8s/base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobportal
  template:
    metadata:
      labels:
        app: jobportal
    spec:
      containers:
        - name: jobportal
          image: himal77/jobportal
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-uri       # ← reads from secret ✅
          resources:
            requests:
              memory: '256Mi'
              cpu: '250m'
            limits:
              memory: '512Mi'
              cpu: '500m'
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30