apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - namespace.yaml
  - ../../base/common

images:
  - name: jobportal
    newName: your-dockerhub-username/jobportal
    newTag: "4.1.0"

patches:
  - path: service-patch.yaml
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: jobportal