apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - namespace.yaml
  - ../../base/common

images:
  - name: himal77/jobportal
    newTag: "3.3.2"

patches:
  - path: service-patch.yaml
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: jobportal