apiVersion: v1
kind: Service
metadata:
  name: jobportal
  namespace: staging
spec:
  selector:
    app: jobportal
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30082
  type: NodePort